/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador_automovil;
import controlador.Controlador_cliente;
import controlador.Controlador_concesionario;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Angel
 */
public class Automovil extends javax.swing.JFrame {

    /**
     * Creates new form Automovil
     */
    public Automovil() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Automoviles");
        
        //Para cargar los clientes
        Controlador_cliente cc=new Controlador_cliente();    
                ArrayList<String> lista=cc.cargarClientes();
                for (int i=0;i<lista.size();i++){
                    veh_cli_select_act.addItem(lista.get(i));//automovil - actualizacion
                    dni_propi_select_insertar.addItem(lista.get(i));//automovil - insertar   
                    dni_act.addItem(lista.get(i));//automovil - insertar   
                }  
                
        //Para cargar los concesionarios        
        Controlador_concesionario ccc=new Controlador_concesionario();
        ArrayList<Integer> listaConcesionarios=ccc.cargarConcesionarios();
                for (int i=0;i<listaConcesionarios.size();i++){
                   cod_conesionario_act.addItem(listaConcesionarios.get(i));
                   cod_concesionario.addItem(listaConcesionarios.get(i));
                }  
        Controlador_automovil ca=new Controlador_automovil();
        ArrayList<String> listaAutos=ca.cargarAutos(null);
        for (int i=0;i<listaAutos.size();i++){
            veh_consulta.addItem(listaAutos.get(i));//automovil - actualizacion
            veh_select_bor.addItem(listaAutos.get(i));//automovil -borrar
        }  
    }
    
    //Para cargar los selects en donde mostremos los vehiculos
    public void RecargarAutos(){
        veh_consulta.removeAllItems();
        veh_select_bor.removeAllItems();     
    //Para cargar los autos en la pestaña consulta
        Controlador_automovil ca=new Controlador_automovil();
        ArrayList<String> listaAutos=ca.cargarAutos(null);
        for (int i=0;i<listaAutos.size();i++){
            veh_consulta.addItem(listaAutos.get(i));//automovil - actualizacion
            veh_select_bor.addItem(listaAutos.get(i));//automovil -borrar
        }  
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        insertar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        matricula = new javax.swing.JTextField();
        color = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        modelo = new javax.swing.JTextField();
        marca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dni_propi_select_insertar = new javax.swing.JComboBox();
        jLabel33 = new javax.swing.JLabel();
        insertar1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        log_insert = new javax.swing.JTextArea();
        cod_concesionario = new javax.swing.JComboBox();
        actualizar = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        veh_cli_select_act = new javax.swing.JComboBox();
        veh_mat_select_act = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        btn_actualizar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        marca_act = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        matricula_act = new javax.swing.JTextField();
        color_act = new javax.swing.JTextField();
        modelo_act = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        log_act = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        cod_conesionario_act = new javax.swing.JComboBox();
        dni_act = new javax.swing.JComboBox();
        borrar = new javax.swing.JPanel();
        veh_select_bor = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        btn_borrar = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        log_bor = new javax.swing.JTextArea();
        consultar = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        btn_consultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        veh_tabla_consultas = new javax.swing.JTable();
        veh_consulta = new javax.swing.JComboBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        navegador = new javax.swing.JMenu();
        automoviles = new javax.swing.JMenuItem();
        clientes = new javax.swing.JMenuItem();
        reparaciones = new javax.swing.JMenuItem();
        mecanicos = new javax.swing.JMenuItem();
        concesionarios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(651, 415));

        insertar.setPreferredSize(new java.awt.Dimension(651, 415));
        insertar.setVerifyInputWhenFocusTarget(false);

        jLabel1.setText("Matricula");

        matricula.setPreferredSize(new java.awt.Dimension(80, 20));
        matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriculaActionPerformed(evt);
            }
        });

        jLabel2.setText("Color");

        jLabel3.setText("Modelo");

        marca.setMinimumSize(new java.awt.Dimension(80, 20));
        marca.setPreferredSize(new java.awt.Dimension(80, 20));

        jLabel4.setText("Marca");

        jLabel6.setText("Codigo concesionario");

        dni_propi_select_insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dni_propi_select_insertarActionPerformed(evt);
            }
        });

        jLabel33.setText("Dni propietario");

        insertar1.setText("Insertar");
        insertar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertar1ActionPerformed(evt);
            }
        });

        jLabel20.setText("Log : ");

        log_insert.setColumns(20);
        log_insert.setRows(5);
        jScrollPane3.setViewportView(log_insert);

        cod_concesionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cod_concesionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout insertarLayout = new javax.swing.GroupLayout(insertar);
        insertar.setLayout(insertarLayout);
        insertarLayout.setHorizontalGroup(
            insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, insertarLayout.createSequentialGroup()
                .addContainerGap(298, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cod_concesionario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dni_propi_select_insertar, 0, 80, Short.MAX_VALUE)))
                .addGap(163, 163, 163))
            .addGroup(insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(insertarLayout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addGroup(insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3)
                        .addGroup(insertarLayout.createSequentialGroup()
                            .addGroup(insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(color)
                                .addComponent(modelo)
                                .addComponent(matricula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel33))
                            .addGap(272, 272, 272))
                        .addGroup(insertarLayout.createSequentialGroup()
                            .addGroup(insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(insertar1)
                                .addComponent(jLabel20))
                            .addGap(555, 555, 555)))
                    .addGap(13, 13, 13)))
        );
        insertarLayout.setVerticalGroup(
            insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertarLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cod_concesionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dni_propi_select_insertar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(221, Short.MAX_VALUE))
            .addGroup(insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(insertarLayout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addGroup(insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addGroup(insertarLayout.createSequentialGroup()
                            .addGroup(insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel33))))
                    .addGap(18, 18, 18)
                    .addComponent(insertar1)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel20)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(47, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Insertar", insertar);

        jLabel34.setText("Elige un cliente");

        veh_cli_select_act.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                veh_cli_select_actItemStateChanged(evt);
            }
        });
        veh_cli_select_act.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veh_cli_select_actActionPerformed(evt);
            }
        });

        veh_mat_select_act.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                veh_mat_select_actItemStateChanged(evt);
            }
        });
        veh_mat_select_act.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veh_mat_select_actActionPerformed(evt);
            }
        });

        jLabel11.setText("Elige un vehiculo");

        btn_actualizar.setText("Actualizar");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        jLabel10.setText("Marca");

        marca_act.setMinimumSize(new java.awt.Dimension(80, 20));
        marca_act.setPreferredSize(new java.awt.Dimension(80, 20));

        jLabel9.setText("Codigo concesionario");

        jLabel5.setText("Matricula");

        matricula_act.setPreferredSize(new java.awt.Dimension(80, 20));
        matricula_act.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matricula_actActionPerformed(evt);
            }
        });

        jLabel7.setText("Color");

        jLabel8.setText("Modelo");

        jLabel35.setText("Dni propietario");

        log_act.setColumns(20);
        log_act.setRows(5);
        jScrollPane4.setViewportView(log_act);

        jLabel21.setText("Log : ");

        cod_conesionario_act.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cod_conesionario_actActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout actualizarLayout = new javax.swing.GroupLayout(actualizar);
        actualizar.setLayout(actualizarLayout);
        actualizarLayout.setHorizontalGroup(
            actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actualizarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(actualizarLayout.createSequentialGroup()
                        .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(actualizarLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane4))
                        .addContainerGap())
                    .addGroup(actualizarLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel34)
                            .addComponent(btn_actualizar))
                        .addGap(44, 44, 44)
                        .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(veh_cli_select_act, 0, 80, Short.MAX_VALUE)
                            .addComponent(veh_mat_select_act, 0, 80, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                        .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(actualizarLayout.createSequentialGroup()
                                .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel35))
                                .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(actualizarLayout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addComponent(matricula_act, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, actualizarLayout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(modelo_act, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                            .addComponent(dni_act, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(actualizarLayout.createSequentialGroup()
                                .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(marca_act, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cod_conesionario_act, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, actualizarLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(color_act, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50))))
        );
        actualizarLayout.setVerticalGroup(
            actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actualizarLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(actualizarLayout.createSequentialGroup()
                        .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(veh_cli_select_act, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34))
                        .addGap(18, 18, 18)
                        .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(veh_mat_select_act, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addGroup(actualizarLayout.createSequentialGroup()
                        .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(marca_act, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cod_conesionario_act, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(matricula_act, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(8, 8, 8)
                        .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(color_act, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modelo_act, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(btn_actualizar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addComponent(dni_act, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jTabbedPane1.addTab("Actualizar", actualizar);

        veh_select_bor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veh_select_borActionPerformed(evt);
            }
        });

        jLabel22.setText("Elige un vehiculo a borrar");

        btn_borrar.setText("Borrar");
        btn_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrarActionPerformed(evt);
            }
        });

        jLabel23.setText("Log : ");

        log_bor.setColumns(20);
        log_bor.setRows(5);
        jScrollPane5.setViewportView(log_bor);

        javax.swing.GroupLayout borrarLayout = new javax.swing.GroupLayout(borrar);
        borrar.setLayout(borrarLayout);
        borrarLayout.setHorizontalGroup(
            borrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(borrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(borrarLayout.createSequentialGroup()
                        .addGroup(borrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, borrarLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(veh_select_bor, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(borrarLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(205, 205, 205)))
                        .addGap(0, 410, Short.MAX_VALUE))
                    .addGroup(borrarLayout.createSequentialGroup()
                        .addGroup(borrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5)
                            .addGroup(borrarLayout.createSequentialGroup()
                                .addComponent(btn_borrar)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        borrarLayout.setVerticalGroup(
            borrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borrarLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(borrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(veh_select_bor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(46, 46, 46)
                .addComponent(btn_borrar)
                .addGap(38, 38, 38)
                .addComponent(jLabel23)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jTabbedPane1.addTab("Borrar", borrar);

        jLabel36.setText("Matricula:");

        btn_consultar.setText("Consultar");
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });

        veh_tabla_consultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Matricula", "Dni_propietario", "Cod_concesionario", "Marca", "Modelo", "Color"
            }
        ));
        jScrollPane1.setViewportView(veh_tabla_consultas);

        javax.swing.GroupLayout consultarLayout = new javax.swing.GroupLayout(consultar);
        consultar.setLayout(consultarLayout);
        consultarLayout.setHorizontalGroup(
            consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
            .addGroup(consultarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(consultarLayout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(veh_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_consultar))
                .addContainerGap(504, Short.MAX_VALUE))
        );
        consultarLayout.setVerticalGroup(
            consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultarLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(veh_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_consultar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consultar", consultar);

        navegador.setText("Navegador");
        navegador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navegadorActionPerformed(evt);
            }
        });

        automoviles.setText("Automoviles");
        automoviles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                automovilesActionPerformed(evt);
            }
        });
        navegador.add(automoviles);

        clientes.setText("Clientes");
        clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesActionPerformed(evt);
            }
        });
        navegador.add(clientes);

        reparaciones.setText("Reparaciones");
        reparaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reparacionesActionPerformed(evt);
            }
        });
        navegador.add(reparaciones);

        mecanicos.setText("Mecanicos");
        mecanicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mecanicosActionPerformed(evt);
            }
        });
        navegador.add(mecanicos);

        concesionarios.setText("Concesionarios");
        concesionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concesionariosActionPerformed(evt);
            }
        });
        navegador.add(concesionarios);

        jMenuBar1.add(navegador);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void automovilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_automovilesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_automovilesActionPerformed

    private void clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesActionPerformed
        // TODO add your handling code here:
        Cliente obj=new Cliente();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_clientesActionPerformed

    private void navegadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navegadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_navegadorActionPerformed

    private void reparacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reparacionesActionPerformed
       Reparaciones obj=new Reparaciones();
       obj.setVisible(true);
       dispose();
        
    }//GEN-LAST:event_reparacionesActionPerformed

    private void mecanicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mecanicosActionPerformed
       Mecanico obj=new Mecanico();
       obj.setVisible(true);
       dispose();
    }//GEN-LAST:event_mecanicosActionPerformed

    private void concesionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concesionariosActionPerformed
        Concesionarios obj=new Concesionarios();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_concesionariosActionPerformed

    private void matriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matriculaActionPerformed

    private void insertar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertar1ActionPerformed
        //Mandamos los datos a insertar a traves del controlador
        Controlador_automovil ca=new Controlador_automovil(matricula.getText(),modelo.getText(),color.getText(),
        marca.getText(),Integer.parseInt(cod_concesionario.getSelectedItem().toString()),dni_propi_select_insertar.getSelectedItem().toString());

        //Para la consulta
        RecargarAutos();
        
        //Cogemos el log y lo insertamos
        log_insert.setText(ca.getLog());
    }//GEN-LAST:event_insertar1ActionPerformed

    private void veh_cli_select_actItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_veh_cli_select_actItemStateChanged
        //Creamos la instancia del controlador
        Controlador_automovil ca=new Controlador_automovil();

        //Consultamos los datos
        ArrayList<String> autos=ca.cargarAutos(veh_cli_select_act.getSelectedItem().toString());//Le pasamos el dni del cliente
        
        veh_mat_select_act.removeAllItems();
        //Cargamos los datos devueltos a los comboboxes
        for (int i=0;i<autos.size();i++){
            veh_mat_select_act.addItem(autos.get(i));
        }
        // veh_mat_select_act.repaint();//repintamos
    }//GEN-LAST:event_veh_cli_select_actItemStateChanged

    private void veh_cli_select_actActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veh_cli_select_actActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_veh_cli_select_actActionPerformed

    private void veh_mat_select_actItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_veh_mat_select_actItemStateChanged
        
        if(evt.getStateChange()==ItemEvent.SELECTED){  

            Controlador_automovil ca=new Controlador_automovil();
            ca.recogerDatosVehiculo(veh_cli_select_act.getSelectedItem().toString(), veh_mat_select_act.getSelectedItem().toString());

            marca_act.setText(ca.getMarca());
            modelo_act.setText(ca.getModelo());
            matricula_act.setText(ca.getMatricula());
            dni_act.setSelectedItem(ca.getDni_propietario());
            color_act.setText(ca.getColor());
            cod_conesionario_act.setSelectedItem(ca.getCod_concesionario());

        }
           
    }//GEN-LAST:event_veh_mat_select_actItemStateChanged

    private void veh_mat_select_actActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veh_mat_select_actActionPerformed
        
    }//GEN-LAST:event_veh_mat_select_actActionPerformed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        Controlador_automovil ca =new Controlador_automovil();
        if(!"".equals(dni_act.getSelectedItem().toString())){
            ca.actualizar_Automovil(veh_mat_select_act.getSelectedItem().toString(),matricula_act.getText(),modelo_act.getText(),color_act.getText(),
                 marca_act.getText(),Integer.parseInt(cod_conesionario_act.getSelectedItem().toString()),dni_act.getSelectedItem().toString());
        }

        //Cogemos el log y lo insertamos
        log_act.setText(ca.getLog());
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void matricula_actActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matricula_actActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matricula_actActionPerformed

    private void btn_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrarActionPerformed
        Controlador_automovil ca =new Controlador_automovil();
        ca.borrarAuto(veh_select_bor.getSelectedItem().toString());
        RecargarAutos();

    }//GEN-LAST:event_btn_borrarActionPerformed

    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed
        // TODO add your handling code here:
        Controlador_automovil ca=new Controlador_automovil();

        ArrayList<ArrayList<String>>listaAutos=ca.consultaVehiculos(veh_consulta.getSelectedItem().toString());
        DefaultTableModel modelo;
        modelo=(DefaultTableModel) veh_tabla_consultas.getModel();
        for(int i=0;i<listaAutos.size();i++){
            modelo.insertRow(i, listaAutos.get(i).toArray());
        }
        veh_tabla_consultas.setModel(modelo);

    }//GEN-LAST:event_btn_consultarActionPerformed

    private void dni_propi_select_insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dni_propi_select_insertarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dni_propi_select_insertarActionPerformed

    private void cod_conesionario_actActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cod_conesionario_actActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cod_conesionario_actActionPerformed

    private void cod_concesionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cod_concesionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cod_concesionarioActionPerformed

    private void veh_select_borActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veh_select_borActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_veh_select_borActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Automovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Automovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Automovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Automovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Automovil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actualizar;
    private javax.swing.JMenuItem automoviles;
    private javax.swing.JPanel borrar;
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_borrar;
    private javax.swing.JButton btn_consultar;
    private javax.swing.JMenuItem clientes;
    private javax.swing.JComboBox cod_concesionario;
    private javax.swing.JComboBox cod_conesionario_act;
    private javax.swing.JTextField color;
    private javax.swing.JTextField color_act;
    private javax.swing.JMenuItem concesionarios;
    private javax.swing.JPanel consultar;
    private javax.swing.JComboBox dni_act;
    private javax.swing.JComboBox dni_propi_select_insertar;
    private javax.swing.JPanel insertar;
    private javax.swing.JButton insertar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea log_act;
    private javax.swing.JTextArea log_bor;
    private javax.swing.JTextArea log_insert;
    private javax.swing.JTextField marca;
    private javax.swing.JTextField marca_act;
    private javax.swing.JTextField matricula;
    private javax.swing.JTextField matricula_act;
    private javax.swing.JMenuItem mecanicos;
    private javax.swing.JTextField modelo;
    private javax.swing.JTextField modelo_act;
    private javax.swing.JMenu navegador;
    private javax.swing.JMenuItem reparaciones;
    private javax.swing.JComboBox veh_cli_select_act;
    private javax.swing.JComboBox veh_consulta;
    private javax.swing.JComboBox veh_mat_select_act;
    private javax.swing.JComboBox veh_select_bor;
    private javax.swing.JTable veh_tabla_consultas;
    // End of variables declaration//GEN-END:variables
}
