/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import controlador.Controlador_concesionario;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Angel
 */
public class Concesionarios extends javax.swing.JFrame {

    /**
     * Creates new form Concesionarios
     */
    public Concesionarios() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Concesionarios");
        
        
        Controlador_concesionario cc=new Controlador_concesionario();    
                ArrayList<Integer> lista=cc.cargarConcesionarios();
                for (int i=0;i<lista.size();i++){
                    act_select_cod.addItem(lista.get(i));//select cliente actualizar
                    bor_select_cod.addItem(lista.get(i));//select cliente borrar
                    con_cod.addItem(lista.get(i));
                }   
           
    }

    public void RecargarConcesionarios(){
        act_select_cod.removeAllItems();
        bor_select_cod.removeAllItems();
        con_cod.removeAllItems();
        
        Controlador_concesionario cc=new Controlador_concesionario();    
                ArrayList<Integer> lista=cc.cargarConcesionarios();
                for (int i=0;i<lista.size();i++){
                    act_select_cod.addItem(lista.get(i));//select cliente actualizar
                    bor_select_cod.addItem(lista.get(i));//select cliente borrar
                    con_cod.addItem(lista.get(i));
                }   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        insertar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ins_cod_conce = new javax.swing.JTextField();
        ins_nombre = new javax.swing.JTextField();
        ins_dir = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ins_log = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        btn_insertar = new javax.swing.JButton();
        actualizar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        act_cod_conce = new javax.swing.JTextField();
        act_nombre = new javax.swing.JTextField();
        act_dir = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_actualizar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        act_log = new javax.swing.JTextArea();
        act_select_cod = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        borrar = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        bor_select_cod = new javax.swing.JComboBox();
        btn_borrar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        bor_log = new javax.swing.JTextArea();
        consultar = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        con_cod = new javax.swing.JComboBox();
        btn_consultar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabla_consultas = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        navegador = new javax.swing.JMenu();
        automoviles = new javax.swing.JMenuItem();
        clientes = new javax.swing.JMenuItem();
        reparaciones = new javax.swing.JMenuItem();
        mecanicos = new javax.swing.JMenuItem();
        concesionarios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Codigo concesionario");

        jLabel2.setText("Nombre");

        jLabel3.setText("Direccion");

        ins_log.setColumns(20);
        ins_log.setRows(5);
        jScrollPane1.setViewportView(ins_log);

        jLabel4.setText("Log:");

        btn_insertar.setText("Insertar");
        btn_insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout insertarLayout = new javax.swing.GroupLayout(insertar);
        insertar.setLayout(insertarLayout);
        insertarLayout.setHorizontalGroup(
            insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                    .addGroup(insertarLayout.createSequentialGroup()
                        .addGroup(insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(insertarLayout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(ins_cod_conce, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                                .addGroup(insertarLayout.createSequentialGroup()
                                    .addGroup(insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(insertarLayout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(79, 79, 79))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, insertarLayout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(73, 73, 73)))
                                    .addGap(3, 3, 3)
                                    .addGroup(insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ins_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                        .addComponent(ins_dir))))
                            .addComponent(btn_insertar))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        insertarLayout.setVerticalGroup(
            insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertarLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(insertarLayout.createSequentialGroup()
                        .addGroup(insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(ins_cod_conce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3))
                    .addGroup(insertarLayout.createSequentialGroup()
                        .addComponent(ins_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ins_dir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addComponent(btn_insertar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Insertar", insertar);

        jLabel5.setText("Codigo concesionario");

        jLabel6.setText("Nombre");

        jLabel7.setText("Direccion");

        btn_actualizar.setText("Actualizar");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        jLabel8.setText("Log:");

        act_log.setColumns(20);
        act_log.setRows(5);
        jScrollPane2.setViewportView(act_log);

        act_select_cod.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                act_select_codItemStateChanged(evt);
            }
        });

        jLabel9.setText("Elige concesionario");

        javax.swing.GroupLayout actualizarLayout = new javax.swing.GroupLayout(actualizar);
        actualizar.setLayout(actualizarLayout);
        actualizarLayout.setHorizontalGroup(
            actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actualizarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                    .addGroup(actualizarLayout.createSequentialGroup()
                        .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(btn_actualizar)
                            .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(actualizarLayout.createSequentialGroup()
                                    .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(actualizarLayout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(79, 79, 79))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, actualizarLayout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addGap(73, 73, 73)))
                                    .addGap(3, 3, 3)
                                    .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(act_nombre)
                                        .addComponent(act_dir, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(actualizarLayout.createSequentialGroup()
                                    .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(18, 18, 18)
                                    .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(act_select_cod, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(act_cod_conce, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        actualizarLayout.setVerticalGroup(
            actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actualizarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(act_select_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(actualizarLayout.createSequentialGroup()
                        .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(act_cod_conce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel7))
                    .addGroup(actualizarLayout.createSequentialGroup()
                        .addComponent(act_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(act_dir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btn_actualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Actualizar", actualizar);

        jLabel10.setText("Elige concesionario");

        btn_borrar.setText("Borrar");
        btn_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrarActionPerformed(evt);
            }
        });

        jLabel11.setText("Log:");

        bor_log.setColumns(20);
        bor_log.setRows(5);
        jScrollPane3.setViewportView(bor_log);

        javax.swing.GroupLayout borrarLayout = new javax.swing.GroupLayout(borrar);
        borrar.setLayout(borrarLayout);
        borrarLayout.setHorizontalGroup(
            borrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_borrar)
                .addContainerGap(573, Short.MAX_VALUE))
            .addGroup(borrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(borrarLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(borrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                        .addGroup(borrarLayout.createSequentialGroup()
                            .addGroup(borrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addGroup(borrarLayout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(18, 18, 18)
                                    .addComponent(bor_select_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        borrarLayout.setVerticalGroup(
            borrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borrarLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(btn_borrar)
                .addContainerGap(213, Short.MAX_VALUE))
            .addGroup(borrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(borrarLayout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addGroup(borrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bor_select_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                    .addComponent(jLabel11)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16)))
        );

        jTabbedPane1.addTab("Borrar", borrar);

        jLabel12.setText("Elige concesionario");

        btn_consultar.setText("Consultar");
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });

        tabla_consultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cod_concesionario", "Nombre", "Direccion"
            }
        ));
        jScrollPane4.setViewportView(tabla_consultas);

        javax.swing.GroupLayout consultarLayout = new javax.swing.GroupLayout(consultar);
        consultar.setLayout(consultarLayout);
        consultarLayout.setHorizontalGroup(
            consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                    .addGroup(consultarLayout.createSequentialGroup()
                        .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(consultarLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(con_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_consultar))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        consultarLayout.setVerticalGroup(
            consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(con_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addComponent(btn_consultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        jTabbedPane1.addTab("Consultar", consultar);

        navegador.setText("Navegador");
        navegador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navegadorActionPerformed(evt);
            }
        });

        automoviles.setText("Automoviles");
        automoviles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                automovilesActionPerformed(evt);
            }
        });
        navegador.add(automoviles);

        clientes.setText("Clientes");
        clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesActionPerformed(evt);
            }
        });
        navegador.add(clientes);

        reparaciones.setText("Reparaciones");
        reparaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reparacionesActionPerformed(evt);
            }
        });
        navegador.add(reparaciones);

        mecanicos.setText("Mecanicos");
        mecanicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mecanicosActionPerformed(evt);
            }
        });
        navegador.add(mecanicos);

        concesionarios.setText("Concesionarios");
        navegador.add(concesionarios);

        jMenuBar1.add(navegador);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void automovilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_automovilesActionPerformed
        Automovil obj=new Automovil();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_automovilesActionPerformed

    private void clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesActionPerformed
        // TODO add your handling code here:
        Cliente obj=new Cliente();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_clientesActionPerformed

         
    private void navegadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navegadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_navegadorActionPerformed

    private void reparacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reparacionesActionPerformed
         Reparaciones obj=new Reparaciones();
       obj.setVisible(true);
       dispose();
    }//GEN-LAST:event_reparacionesActionPerformed

    private void mecanicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mecanicosActionPerformed
        Mecanico obj=new Mecanico();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_mecanicosActionPerformed

    private void btn_insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertarActionPerformed
    Controlador_concesionario co=new Controlador_concesionario(new Integer(ins_cod_conce.getText()),
                                                                ins_nombre.getText(),
                                                                ins_dir.getText());
    ins_log.setText(co.getLog());
    RecargarConcesionarios();
    }//GEN-LAST:event_btn_insertarActionPerformed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        Controlador_concesionario cc=new Controlador_concesionario();
        cc.actualizar_Concesionario(new Integer(act_select_cod.getSelectedItem().toString()),new Integer(act_cod_conce.getText()), act_nombre.getText(), act_dir.getText());
        act_log.setText(cc.getLog());
        RecargarConcesionarios();
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void btn_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrarActionPerformed
        Controlador_concesionario co=new Controlador_concesionario();
        co.borrarConcesionario(bor_select_cod.getSelectedItem().toString());
        bor_log.setText(co.getLog());
        RecargarConcesionarios();
    }//GEN-LAST:event_btn_borrarActionPerformed

    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed
        Controlador_concesionario ca=new  Controlador_concesionario();

        ArrayList<ArrayList<String>>listaConcecionarios=ca.consultaConcesionario(new Integer (con_cod.getSelectedItem().toString()));
        DefaultTableModel modelo;
        modelo=(DefaultTableModel) tabla_consultas.getModel();
        for(int i=0;i<listaConcecionarios.size();i++){
            modelo.insertRow(i, listaConcecionarios.get(i).toArray());
        }
        tabla_consultas.setModel(modelo);
        
        
    }//GEN-LAST:event_btn_consultarActionPerformed

    private void act_select_codItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_act_select_codItemStateChanged
        if(evt.getStateChange()==ItemEvent.SELECTED){
            // TODO add your handling code here:
            Controlador_concesionario ca=new  Controlador_concesionario();
            ca.recogerDatosConcesionario(new Integer(act_select_cod.getSelectedItem().toString()));
            act_cod_conce.setText(Integer.toString(ca.getCod_concesionario()));
            act_nombre.setText(ca.getNombre());
            act_dir.setText(ca.getDireccion());
        }    
    }//GEN-LAST:event_act_select_codItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Concesionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Concesionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Concesionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Concesionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Concesionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField act_cod_conce;
    private javax.swing.JTextField act_dir;
    private javax.swing.JTextArea act_log;
    private javax.swing.JTextField act_nombre;
    private javax.swing.JComboBox act_select_cod;
    private javax.swing.JPanel actualizar;
    private javax.swing.JMenuItem automoviles;
    private javax.swing.JTextArea bor_log;
    private javax.swing.JComboBox bor_select_cod;
    private javax.swing.JPanel borrar;
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_borrar;
    private javax.swing.JButton btn_consultar;
    private javax.swing.JButton btn_insertar;
    private javax.swing.JMenuItem clientes;
    private javax.swing.JComboBox con_cod;
    private javax.swing.JMenuItem concesionarios;
    private javax.swing.JPanel consultar;
    private javax.swing.JTextField ins_cod_conce;
    private javax.swing.JTextField ins_dir;
    private javax.swing.JTextArea ins_log;
    private javax.swing.JTextField ins_nombre;
    private javax.swing.JPanel insertar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem mecanicos;
    private javax.swing.JMenu navegador;
    private javax.swing.JMenuItem reparaciones;
    private javax.swing.JTable tabla_consultas;
    // End of variables declaration//GEN-END:variables
}
