/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador_mecanico;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Angel
 */
public class Mecanico extends javax.swing.JFrame {

    /**
     * Creates new form Mecanico
     */
    public Mecanico() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Mecanicos");
        //Para cargar los mecanicos
        Controlador_mecanico cc=new Controlador_mecanico();    
                ArrayList<String> lista=cc.cargarMecanicos();
                for (int i=0;i<lista.size();i++){
                    act_mec_select.addItem(lista.get(i));//select cliente actualizar
                    bor_mec_select.addItem(lista.get(i));//select cliente borrar
                    con_dni.addItem(lista.get(i));
                }   
        
        
        
    }

    public void RecargarMecanicos(){
        act_mec_select.removeAllItems();//select cliente actualizar
        bor_mec_select.removeAllItems();//select cliente borrar
        con_dni.removeAllItems();
        //Para cargar los mecanicos
        Controlador_mecanico cc=new Controlador_mecanico();    
                ArrayList<String> lista=cc.cargarMecanicos();
                for (int i=0;i<lista.size();i++){
                    act_mec_select.addItem(lista.get(i));//select cliente actualizar
                    bor_mec_select.addItem(lista.get(i));//select cliente borrar
                    con_dni.addItem(lista.get(i));
                }   
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        insertar = new javax.swing.JPanel();
        insertar1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        ins_dni = new javax.swing.JTextField();
        ins_nombre = new javax.swing.JTextField();
        ins_ape1 = new javax.swing.JTextField();
        ins_ape2 = new javax.swing.JTextField();
        ins_dir = new javax.swing.JTextField();
        ins_tlf = new javax.swing.JTextField();
        btn_insertar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ins_log = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        ins_sal = new javax.swing.JTextField();
        ins_contra = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        actualizar = new javax.swing.JPanel();
        actualizar1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        act_mec_select = new javax.swing.JComboBox();
        act_dni = new javax.swing.JTextField();
        act_nombre = new javax.swing.JTextField();
        act_ape1 = new javax.swing.JTextField();
        act_ape2 = new javax.swing.JTextField();
        act_tlf = new javax.swing.JTextField();
        act_dir = new javax.swing.JTextField();
        btn_actualizar = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        act_log = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        act_sal = new javax.swing.JTextField();
        act_contra = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        borrar = new javax.swing.JPanel();
        borrar1 = new javax.swing.JPanel();
        bor_mec_select = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        btn_borrar = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        bor_log = new javax.swing.JTextArea();
        consultar = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        btn_consultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_consultas = new javax.swing.JTable();
        con_dni = new javax.swing.JComboBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        navegador = new javax.swing.JMenu();
        automoviles = new javax.swing.JMenuItem();
        clientes = new javax.swing.JMenuItem();
        reparaciones = new javax.swing.JMenuItem();
        mecanicos = new javax.swing.JMenuItem();
        concesionarios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel13.setText("Dni propietario");

        jLabel14.setText("Nombre");

        jLabel15.setText("Primer apellido");

        jLabel16.setText("Segundo apellido");

        jLabel17.setText("Telefono");

        jLabel18.setText("Direccion");

        ins_dir.setPreferredSize(new java.awt.Dimension(80, 20));

        btn_insertar.setText("Insertar");
        btn_insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertarActionPerformed(evt);
            }
        });

        jLabel19.setText("Log : ");

        ins_log.setColumns(20);
        ins_log.setRows(5);
        jScrollPane2.setViewportView(ins_log);

        jLabel1.setText("Salario");

        jLabel2.setText("Contratacion");

        javax.swing.GroupLayout insertar1Layout = new javax.swing.GroupLayout(insertar1);
        insertar1.setLayout(insertar1Layout);
        insertar1Layout.setHorizontalGroup(
            insertar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertar1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(insertar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(insertar1Layout.createSequentialGroup()
                        .addGroup(insertar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(insertar1Layout.createSequentialGroup()
                                .addGroup(insertar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(insertar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(insertar1Layout.createSequentialGroup()
                                            .addComponent(jLabel16)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(ins_ape2))
                                        .addGroup(insertar1Layout.createSequentialGroup()
                                            .addComponent(jLabel15)
                                            .addGap(22, 22, 22)
                                            .addComponent(ins_ape1))
                                        .addGroup(insertar1Layout.createSequentialGroup()
                                            .addComponent(jLabel14)
                                            .addGap(54, 54, 54)
                                            .addComponent(ins_nombre))
                                        .addGroup(insertar1Layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addGap(21, 21, 21)
                                            .addComponent(ins_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(btn_insertar))
                                .addGap(169, 169, 169)
                                .addGroup(insertar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18)
                                    .addGroup(insertar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel17))
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(insertar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ins_sal)
                                    .addComponent(ins_dir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ins_tlf)
                                    .addComponent(ins_contra)))
                            .addComponent(jLabel19))
                        .addGap(0, 124, Short.MAX_VALUE)))
                .addContainerGap())
        );
        insertar1Layout.setVerticalGroup(
            insertar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertar1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(insertar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel18)
                    .addComponent(ins_dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ins_dir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(insertar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel17)
                    .addComponent(ins_tlf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ins_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(insertar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(insertar1Layout.createSequentialGroup()
                        .addGroup(insertar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(ins_ape1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(insertar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(ins_ape2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(btn_insertar))
                    .addGroup(insertar1Layout.createSequentialGroup()
                        .addGroup(insertar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ins_sal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(insertar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(ins_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout insertarLayout = new javax.swing.GroupLayout(insertar);
        insertar.setLayout(insertarLayout);
        insertarLayout.setHorizontalGroup(
            insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(insertar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        insertarLayout.setVerticalGroup(
            insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertarLayout.createSequentialGroup()
                .addComponent(insertar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Insertar", insertar);

        jLabel12.setText("Elige un mecanico");

        jLabel26.setText("Dni propietario");

        jLabel27.setText("Nombre");

        jLabel28.setText("Primer apellido");

        jLabel29.setText("Segundo apellido");

        jLabel30.setText("Telefono");

        jLabel31.setText("Direccion");

        act_mec_select.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                act_mec_selectItemStateChanged(evt);
            }
        });

        act_dni.setMinimumSize(new java.awt.Dimension(80, 20));
        act_dni.setPreferredSize(new java.awt.Dimension(80, 20));

        btn_actualizar.setText("Actualizar");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        jLabel32.setText("Log : ");

        act_log.setColumns(20);
        act_log.setRows(5);
        jScrollPane7.setViewportView(act_log);

        jLabel3.setText("Salario");

        jLabel4.setText("Contratacion");

        javax.swing.GroupLayout actualizar1Layout = new javax.swing.GroupLayout(actualizar1);
        actualizar1.setLayout(actualizar1Layout);
        actualizar1Layout.setHorizontalGroup(
            actualizar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actualizar1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(actualizar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(actualizar1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(30, 30, 30)
                        .addComponent(act_mec_select, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane7)
                    .addGroup(actualizar1Layout.createSequentialGroup()
                        .addGroup(actualizar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_actualizar)
                            .addComponent(jLabel32)
                            .addGroup(actualizar1Layout.createSequentialGroup()
                                .addGroup(actualizar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(actualizar1Layout.createSequentialGroup()
                                        .addGap(328, 328, 328)
                                        .addGroup(actualizar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel31)
                                            .addGroup(actualizar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel30))))
                                    .addGroup(actualizar1Layout.createSequentialGroup()
                                        .addGroup(actualizar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel26)
                                            .addComponent(jLabel27)
                                            .addComponent(jLabel28)
                                            .addComponent(jLabel29))
                                        .addGap(18, 18, 18)
                                        .addGroup(actualizar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(act_ape2)
                                            .addComponent(act_ape1)
                                            .addComponent(act_nombre)
                                            .addComponent(act_dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(actualizar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(act_dir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(act_tlf, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(actualizar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(act_contra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                        .addComponent(act_sal, javax.swing.GroupLayout.Alignment.LEADING)))))
                        .addGap(123, 123, 123)))
                .addContainerGap())
        );
        actualizar1Layout.setVerticalGroup(
            actualizar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actualizar1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(actualizar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(act_mec_select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(actualizar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(act_dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(act_dir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(actualizar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(act_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(act_tlf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel30))
                .addGap(10, 10, 10)
                .addGroup(actualizar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(act_ape1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(act_sal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(actualizar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(act_ape2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(act_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(39, 39, 39)
                .addComponent(btn_actualizar)
                .addGap(18, 18, 18)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout actualizarLayout = new javax.swing.GroupLayout(actualizar);
        actualizar.setLayout(actualizarLayout);
        actualizarLayout.setHorizontalGroup(
            actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actualizarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(actualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        actualizarLayout.setVerticalGroup(
            actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, actualizarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(actualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Actualizar", actualizar);

        jLabel24.setText("Elige un mecanico");

        btn_borrar.setText("Borrar");
        btn_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrarActionPerformed(evt);
            }
        });

        jLabel25.setText("Log : ");

        bor_log.setColumns(20);
        bor_log.setRows(5);
        jScrollPane6.setViewportView(bor_log);

        javax.swing.GroupLayout borrar1Layout = new javax.swing.GroupLayout(borrar1);
        borrar1.setLayout(borrar1Layout);
        borrar1Layout.setHorizontalGroup(
            borrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borrar1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(borrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(borrar1Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addComponent(bor_mec_select, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_borrar)
                    .addComponent(jLabel25))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        borrar1Layout.setVerticalGroup(
            borrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borrar1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(borrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(bor_mec_select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btn_borrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout borrarLayout = new javax.swing.GroupLayout(borrar);
        borrar.setLayout(borrarLayout);
        borrarLayout.setHorizontalGroup(
            borrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 696, Short.MAX_VALUE)
            .addGroup(borrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(borrarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(borrar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        borrarLayout.setVerticalGroup(
            borrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
            .addGroup(borrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(borrarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(borrar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Borrar", borrar);

        jLabel36.setText("Dni");

        btn_consultar.setText("Consultar");
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });

        tabla_consultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Dni", "Nombre", "Apellido1", "Apellido2", "Direccion", "Telefono", "Salario", "Contratacion"
            }
        ));
        jScrollPane1.setViewportView(tabla_consultas);

        javax.swing.GroupLayout consultarLayout = new javax.swing.GroupLayout(consultar);
        consultar.setLayout(consultarLayout);
        consultarLayout.setHorizontalGroup(
            consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
            .addGroup(consultarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(consultarLayout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(con_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_consultar))
                .addContainerGap(575, Short.MAX_VALUE))
        );
        consultarLayout.setVerticalGroup(
            consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultarLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(con_dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_consultar)
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consultar", consultar);

        navegador.setText("Navegador");
        navegador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navegadorActionPerformed(evt);
            }
        });

        automoviles.setText("Automoviles");
        automoviles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                automovilesActionPerformed(evt);
            }
        });
        navegador.add(automoviles);

        clientes.setText("Clientes");
        clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesActionPerformed(evt);
            }
        });
        navegador.add(clientes);

        reparaciones.setText("Reparaciones");
        reparaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reparacionesActionPerformed(evt);
            }
        });
        navegador.add(reparaciones);

        mecanicos.setText("Mecanicos");
        navegador.add(mecanicos);

        concesionarios.setText("Concesionarios");
        concesionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concesionariosActionPerformed(evt);
            }
        });
        navegador.add(concesionarios);

        jMenuBar1.add(navegador);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
       
    
    private void automovilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_automovilesActionPerformed
        Automovil obj=new Automovil();
        obj.setVisible(true);
        dispose();


    }//GEN-LAST:event_automovilesActionPerformed

    private void clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesActionPerformed
        // TODO add your handling code here:
        Cliente obj=new Cliente();
        obj.setVisible(true);
        dispose();

    }//GEN-LAST:event_clientesActionPerformed
   
    private void navegadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navegadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_navegadorActionPerformed

    private void reparacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reparacionesActionPerformed
        Reparaciones obj=new Reparaciones();
       obj.setVisible(true);
       dispose();
    }//GEN-LAST:event_reparacionesActionPerformed

    private void concesionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concesionariosActionPerformed
        Concesionarios obj=new Concesionarios();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_concesionariosActionPerformed

    private void btn_insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertarActionPerformed
        Controlador_mecanico cc=new Controlador_mecanico(ins_dni.getText(),ins_nombre.getText(),
            ins_ape1.getText(),ins_ape2.getText(),ins_dir.getText(),new Integer(ins_tlf.getText()),new Float(ins_sal.getText()),ins_contra.getText());
        ins_log.setText(cc.getLog());
        RecargarMecanicos();
    }//GEN-LAST:event_btn_insertarActionPerformed

    private void act_mec_selectItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_act_mec_selectItemStateChanged
        // TODO add your handling code here:
        Controlador_mecanico ca=new  Controlador_mecanico();
       if(evt.getStateChange()==ItemEvent.SELECTED){
        ca.recogerDatosMecanico(act_mec_select.getSelectedItem().toString());
        act_dni.setText(ca.getDni());
        act_nombre.setText(ca.getNombre());
        act_ape1.setText(ca.getApellido1());
        act_ape2.setText(ca.getApellido2());
        act_dir.setText(ca.getDireccion());
        act_tlf.setText(Integer.toString(ca.getTlf()));
        act_sal.setText(Float.toString(ca.getSalario()));
        act_contra.setText(Integer.toString(ca.getTlf()));
                
       }
    }//GEN-LAST:event_act_mec_selectItemStateChanged

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        // TODO add your handling code here:
        Controlador_mecanico cc=new Controlador_mecanico();
        cc.actualizar_Mecanico(act_mec_select.getSelectedItem().toString(),act_dni.getText(), act_nombre.getText(), act_ape1.getText(), act_ape2.getText(), act_dir.getText(), new Integer(act_tlf.getText()),new Float(act_sal.getText()),act_contra.getText());
        RecargarMecanicos();
        act_log.setText(cc.getLog());
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void btn_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrarActionPerformed
        // TODO add your handling code here:
        Controlador_mecanico cc=new Controlador_mecanico();
        cc.borrarMecanico(bor_mec_select.getSelectedItem().toString());
        RecargarMecanicos();
        bor_log.setText(cc.getLog());
    }//GEN-LAST:event_btn_borrarActionPerformed

    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed
        // TODO add your handling code here:
        Controlador_mecanico ca=new Controlador_mecanico();

        ArrayList<ArrayList<String>>listaClientes=ca.consultaMecanico(con_dni.getSelectedItem().toString());
        DefaultTableModel modelo;
        modelo=(DefaultTableModel) tabla_consultas.getModel();
        for(int i=0;i<listaClientes.size();i++){
            modelo.insertRow(i, listaClientes.get(i).toArray());
        }
        tabla_consultas.setModel(modelo);
    }//GEN-LAST:event_btn_consultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mecanico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField act_ape1;
    private javax.swing.JTextField act_ape2;
    private javax.swing.JTextField act_contra;
    private javax.swing.JTextField act_dir;
    private javax.swing.JTextField act_dni;
    private javax.swing.JTextArea act_log;
    private javax.swing.JComboBox act_mec_select;
    private javax.swing.JTextField act_nombre;
    private javax.swing.JTextField act_sal;
    private javax.swing.JTextField act_tlf;
    private javax.swing.JPanel actualizar;
    private javax.swing.JPanel actualizar1;
    private javax.swing.JMenuItem automoviles;
    private javax.swing.JTextArea bor_log;
    private javax.swing.JComboBox bor_mec_select;
    private javax.swing.JPanel borrar;
    private javax.swing.JPanel borrar1;
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_borrar;
    private javax.swing.JButton btn_consultar;
    private javax.swing.JButton btn_insertar;
    private javax.swing.JMenuItem clientes;
    private javax.swing.JComboBox con_dni;
    private javax.swing.JMenuItem concesionarios;
    private javax.swing.JPanel consultar;
    private javax.swing.JTextField ins_ape1;
    private javax.swing.JTextField ins_ape2;
    private javax.swing.JTextField ins_contra;
    private javax.swing.JTextField ins_dir;
    private javax.swing.JTextField ins_dni;
    private javax.swing.JTextArea ins_log;
    private javax.swing.JTextField ins_nombre;
    private javax.swing.JTextField ins_sal;
    private javax.swing.JTextField ins_tlf;
    private javax.swing.JPanel insertar;
    private javax.swing.JPanel insertar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem mecanicos;
    private javax.swing.JMenu navegador;
    private javax.swing.JMenuItem reparaciones;
    private javax.swing.JTable tabla_consultas;
    // End of variables declaration//GEN-END:variables
}
