/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import controlador.Controlador_automovil;
import controlador.Controlador_mecanico;
import controlador.Controlador_repara;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Angel
 */
public class Reparaciones extends javax.swing.JFrame {

    /**
     * Creates new form Reparaciones
     */
    public Reparaciones() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Reparaciones");
        
        //Para cargar las MATRICULAS
        Controlador_repara cc=new Controlador_repara();   
        Controlador_automovil ca = new Controlador_automovil();
        
        ArrayList<String> lista=ca.cargarAllVehicles();
        for (int i=0;i<lista.size();i++){
            //act_matr.addItem(lista.get(i));
            ins_matr.addItem(lista.get(i));
            //bor_matr.addItem(lista.get(i));
        }   
                 
       ArrayList<String> fechas=cc.cargarReparacionFecha();
           for (int i=0;i<fechas.size();i++){
              bor_fecha.addItem(fechas.get(i));
              con_fecha.addItem(fechas.get(i));
              act_sel_fecha.addItem(fechas.get(i));
          }  
       
        //Para cargar mecanicos en actualizar.
        Controlador_mecanico csc=new Controlador_mecanico();   
        ArrayList<String> mecanicos=csc.cargarMecanicos();
           for (int i=0;i<mecanicos.size();i++){
                act_mecanico_n.addItem(mecanicos.get(i));
                ins_mecanico.addItem(mecanicos.get(i));
                
           }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void RecargarFechas(){
        bor_fecha.removeAllItems();
        con_fecha.removeAllItems();
        act_sel_fecha.removeAllItems();
               
        Controlador_repara cc=new Controlador_repara(); 
        //Para cargar las fechas para borrar consultar y actualizar
        ArrayList<String> fechas=cc.cargarReparacionFecha();
           for (int i=0;i<fechas.size();i++){
              bor_fecha.addItem(fechas.get(i));
              con_fecha.addItem(fechas.get(i));
              act_sel_fecha.addItem(fechas.get(i));
          }  
    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        insertar = new javax.swing.JPanel();
        ins_mecanico = new javax.swing.JComboBox();
        ins_matr = new javax.swing.JComboBox();
        lbl_mecanico = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ins_n_horas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ins_log = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        ins_fecha = new javax.swing.JTextField();
        btn_insertar = new javax.swing.JButton();
        actualizar = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        act_log = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        btn_actualizar = new javax.swing.JButton();
        lbl_mecanico1 = new javax.swing.JLabel();
        act_sel_fecha = new javax.swing.JComboBox();
        act_matr = new javax.swing.JComboBox();
        act_n_horas = new javax.swing.JTextField();
        act_fecha = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lbl_mecanico3 = new javax.swing.JLabel();
        act_mecanico_n = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        borrar = new javax.swing.JPanel();
        bor_matr = new javax.swing.JComboBox();
        Matricula = new javax.swing.JLabel();
        btn_borrar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        bor_log = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        bor_fecha = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        consultar = new javax.swing.JPanel();
        btn_consultar = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabla_consultas = new javax.swing.JTable();
        con_fecha = new javax.swing.JComboBox();
        lbl_mecanico2 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        con_matr = new javax.swing.JComboBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        navegador = new javax.swing.JMenu();
        automoviles = new javax.swing.JMenuItem();
        clientes = new javax.swing.JMenuItem();
        reparaciones = new javax.swing.JMenuItem();
        mecanicos = new javax.swing.JMenuItem();
        concesionarios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_mecanico.setText("Mecanico");

        jLabel2.setText("Matricula");

        jLabel3.setText("Num. horas");

        jLabel4.setText("Fecha");

        ins_log.setColumns(20);
        ins_log.setRows(5);
        jScrollPane1.setViewportView(ins_log);

        jLabel5.setText("Log:");

        btn_insertar.setText("Insertar");
        btn_insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout insertarLayout = new javax.swing.GroupLayout(insertar);
        insertar.setLayout(insertarLayout);
        insertarLayout.setHorizontalGroup(
            insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                    .addGroup(insertarLayout.createSequentialGroup()
                        .addGroup(insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(btn_insertar)
                            .addGroup(insertarLayout.createSequentialGroup()
                                .addGroup(insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(lbl_mecanico)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ins_mecanico, 0, 80, Short.MAX_VALUE)
                                    .addComponent(ins_matr, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ins_n_horas)
                                    .addComponent(ins_fecha))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        insertarLayout.setVerticalGroup(
            insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_mecanico)
                    .addComponent(ins_mecanico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ins_matr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(13, 13, 13)
                .addGroup(insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ins_n_horas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ins_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_insertar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Insertar", insertar);

        act_log.setColumns(20);
        act_log.setRows(5);
        jScrollPane3.setViewportView(act_log);

        jLabel11.setText("Log");

        btn_actualizar.setText("Actualizar");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        lbl_mecanico1.setText("Fecha");

        act_sel_fecha.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                act_sel_fechaItemStateChanged(evt);
            }
        });

        act_matr.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                act_matrItemStateChanged(evt);
            }
        });

        jLabel14.setText("Fecha");

        jLabel15.setText("Num. horas");

        jLabel16.setText("Matricula");

        lbl_mecanico3.setText("Mecanico");

        jLabel1.setText("Selecciona estos campos:");

        jLabel6.setText("Actualiza aqui:");

        javax.swing.GroupLayout actualizarLayout = new javax.swing.GroupLayout(actualizar);
        actualizar.setLayout(actualizarLayout);
        actualizarLayout.setHorizontalGroup(
            actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, actualizarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(actualizarLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(act_matr, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(actualizarLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(actualizarLayout.createSequentialGroup()
                        .addComponent(lbl_mecanico1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(act_sel_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(255, 255, 255)
                .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(actualizarLayout.createSequentialGroup()
                            .addComponent(lbl_mecanico3)
                            .addGap(29, 29, 29)
                            .addComponent(act_mecanico_n, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(actualizarLayout.createSequentialGroup()
                            .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15)
                                .addComponent(jLabel14))
                            .addGap(18, 18, 18)
                            .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(act_n_horas, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(act_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(67, 67, 67))
            .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(actualizarLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                        .addGroup(actualizarLayout.createSequentialGroup()
                            .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(btn_actualizar))
                            .addGap(0, 547, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        actualizarLayout.setVerticalGroup(
            actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actualizarLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(actualizarLayout.createSequentialGroup()
                        .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_mecanico3)
                            .addComponent(act_mecanico_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(act_n_horas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(act_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(actualizarLayout.createSequentialGroup()
                        .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_mecanico1)
                            .addComponent(act_sel_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(act_matr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)))
                .addContainerGap(198, Short.MAX_VALUE))
            .addGroup(actualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(actualizarLayout.createSequentialGroup()
                    .addGap(144, 144, 144)
                    .addComponent(btn_actualizar)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                    .addComponent(jLabel11)
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("Actualizar", actualizar);

        bor_matr.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                bor_matrItemStateChanged(evt);
            }
        });

        Matricula.setText("Matriculas");

        btn_borrar.setText("Borrar");
        btn_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrarActionPerformed(evt);
            }
        });

        bor_log.setColumns(20);
        bor_log.setRows(5);
        jScrollPane4.setViewportView(bor_log);

        jLabel19.setText("Log");

        bor_fecha.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                bor_fechaItemStateChanged(evt);
            }
        });

        jLabel7.setText("Fecha");

        javax.swing.GroupLayout borrarLayout = new javax.swing.GroupLayout(borrar);
        borrar.setLayout(borrarLayout);
        borrarLayout.setHorizontalGroup(
            borrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(borrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                    .addGroup(borrarLayout.createSequentialGroup()
                        .addGroup(borrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_borrar)
                            .addComponent(jLabel19)
                            .addGroup(borrarLayout.createSequentialGroup()
                                .addGroup(borrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Matricula)
                                    .addComponent(jLabel7))
                                .addGap(29, 29, 29)
                                .addGroup(borrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bor_fecha, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bor_matr, 0, 80, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        borrarLayout.setVerticalGroup(
            borrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borrarLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(borrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bor_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(borrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Matricula)
                    .addComponent(bor_matr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(btn_borrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Borrar", borrar);

        btn_consultar.setText("Consultar");
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });

        tabla_consultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Matricula", "Mecanico", "num_horas", "fecha"
            }
        ));
        jScrollPane5.setViewportView(tabla_consultas);

        con_fecha.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                con_fechaItemStateChanged(evt);
            }
        });

        lbl_mecanico2.setText("Fecha");

        jLabel20.setText("Matricula");

        javax.swing.GroupLayout consultarLayout = new javax.swing.GroupLayout(consultar);
        consultar.setLayout(consultarLayout);
        consultarLayout.setHorizontalGroup(
            consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(lbl_mecanico2))
                .addGap(18, 18, 18)
                .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(con_fecha, 0, 78, Short.MAX_VALUE)
                    .addComponent(con_matr, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(497, Short.MAX_VALUE))
            .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(consultarLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                        .addComponent(btn_consultar))
                    .addContainerGap()))
        );
        consultarLayout.setVerticalGroup(
            consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_mecanico2)
                    .addComponent(con_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(con_matr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addContainerGap(258, Short.MAX_VALUE))
            .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(consultarLayout.createSequentialGroup()
                    .addGap(120, 120, 120)
                    .addComponent(btn_consultar)
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(75, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Consultar", consultar);

        navegador.setText("Navegador");
        navegador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navegadorActionPerformed(evt);
            }
        });

        automoviles.setText("Automoviles");
        automoviles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                automovilesActionPerformed(evt);
            }
        });
        navegador.add(automoviles);

        clientes.setText("Clientes");
        clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesActionPerformed(evt);
            }
        });
        navegador.add(clientes);

        reparaciones.setText("Reparaciones");
        navegador.add(reparaciones);

        mecanicos.setText("Mecanicos");
        mecanicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mecanicosActionPerformed(evt);
            }
        });
        navegador.add(mecanicos);

        concesionarios.setText("Concesionarios");
        concesionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concesionariosActionPerformed(evt);
            }
        });
        navegador.add(concesionarios);

        jMenuBar1.add(navegador);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void automovilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_automovilesActionPerformed
        // TODO add your handling code here:
        Automovil obj=new Automovil();
        obj.setVisible(true);
        dispose();

    }//GEN-LAST:event_automovilesActionPerformed

    private void clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesActionPerformed
        // TODO add your handling code here:
        Cliente obj=new Cliente();
        obj.setVisible(true);
        dispose();

    }//GEN-LAST:event_clientesActionPerformed
    
    private void navegadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navegadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_navegadorActionPerformed

    private void mecanicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mecanicosActionPerformed
         Mecanico obj=new Mecanico();
       obj.setVisible(true);
       dispose();
    }//GEN-LAST:event_mecanicosActionPerformed

    private void concesionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concesionariosActionPerformed
        Concesionarios obj=new Concesionarios();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_concesionariosActionPerformed

    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed
        Controlador_repara cr= new Controlador_repara();
               
        ArrayList<ArrayList<String>>listaReparaciones=cr.consultaReparaciones(con_matr.getSelectedItem().toString(),con_fecha.getSelectedItem().toString());
        DefaultTableModel modelo;
        modelo=(DefaultTableModel) tabla_consultas.getModel();
        for(int i=0;i<listaReparaciones.size();i++){
            modelo.insertRow(i, listaReparaciones.get(i).toArray());
        }
        tabla_consultas.setModel(modelo);
        
    }//GEN-LAST:event_btn_consultarActionPerformed

    private void btn_insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertarActionPerformed
        Controlador_repara cr= new Controlador_repara();
        cr.insertar_Reparacion(ins_matr.getSelectedItem().toString(), ins_mecanico.getSelectedItem().toString(),Integer.parseInt(ins_n_horas.getText()),ins_fecha.getText());
        RecargarFechas();
        ins_log.setText(cr.getLog());
    }//GEN-LAST:event_btn_insertarActionPerformed

    private void act_matrItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_act_matrItemStateChanged
        if(evt.getStateChange()==ItemEvent.SELECTED){
           Controlador_repara cc=new Controlador_repara();
           cc.recogerDatosReparacion(act_sel_fecha.getSelectedItem().toString(),act_matr.getSelectedItem().toString());

           act_mecanico_n.setSelectedItem(cc.getDni_mecanico());

           act_n_horas.setText(Integer.toString(cc.getN_horas()));
           act_fecha.setText(cc.getFecha());

           
        }
    }//GEN-LAST:event_act_matrItemStateChanged

    private void act_sel_fechaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_act_sel_fechaItemStateChanged
        //Para cargar los dnis de los mecanicos que han reparado el vehiculo 
        if(evt.getStateChange()==ItemEvent.SELECTED){
        Controlador_repara cc=new Controlador_repara();    
                ArrayList<String> lista=cc.cargarMatriculasXFecha(act_sel_fecha.getSelectedItem().toString());
                act_matr.removeAllItems();
                for (int i=0;i<lista.size();i++){
                    act_matr.addItem(lista.get(i));//select cliente actualizar
                }
        }
    }//GEN-LAST:event_act_sel_fechaItemStateChanged

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        Controlador_repara cc=new Controlador_repara();
        cc.actualizar_Reparacion(act_matr.getSelectedItem().toString(),act_mecanico_n.getSelectedItem().toString(),
                Integer.parseInt(act_n_horas.getText()),act_fecha.getText(),act_sel_fecha.getSelectedItem().toString());
        RecargarFechas();
        act_log.setText(cc.getLog());
        
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void btn_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrarActionPerformed
        Controlador_repara cc=new Controlador_repara();
        cc.borrarReparacion(bor_matr.getSelectedItem().toString(), bor_fecha.getSelectedItem().toString());
        RecargarFechas();
        bor_log.setText(cc.getLog());
    }//GEN-LAST:event_btn_borrarActionPerformed

    private void bor_matrItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_bor_matrItemStateChanged
              
    }//GEN-LAST:event_bor_matrItemStateChanged

    private void bor_fechaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_bor_fechaItemStateChanged
        Controlador_repara cc=new Controlador_repara();
       if(evt.getStateChange()==ItemEvent.SELECTED){
            //Para cargar mecanicos SP-> sin parametros 
            bor_matr.removeAllItems();
            ArrayList<String> listam= cc.cargarMatriculasXFecha(bor_fecha.getSelectedItem().toString());
             for (int i=0;i<listam.size();i++){
                bor_matr.addItem(listam.get(i));
            }   
       }
    }//GEN-LAST:event_bor_fechaItemStateChanged

    private void con_fechaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_con_fechaItemStateChanged
        Controlador_repara cc=new Controlador_repara();
        if(evt.getStateChange()==ItemEvent.SELECTED){
            con_matr.removeAllItems();
            ArrayList<String> listam= cc.cargarMatriculasXFecha(con_fecha.getSelectedItem().toString());
            for (int i=0;i<listam.size();i++){
                con_matr.addItem(listam.get(i));
            }   
        } 
    }//GEN-LAST:event_con_fechaItemStateChanged
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reparaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reparaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reparaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reparaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reparaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Matricula;
    private javax.swing.JTextField act_fecha;
    private javax.swing.JTextArea act_log;
    private javax.swing.JComboBox act_matr;
    private javax.swing.JComboBox act_mecanico_n;
    private javax.swing.JTextField act_n_horas;
    private javax.swing.JComboBox act_sel_fecha;
    private javax.swing.JPanel actualizar;
    private javax.swing.JMenuItem automoviles;
    private javax.swing.JComboBox bor_fecha;
    private javax.swing.JTextArea bor_log;
    private javax.swing.JComboBox bor_matr;
    private javax.swing.JPanel borrar;
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_borrar;
    private javax.swing.JButton btn_consultar;
    private javax.swing.JButton btn_insertar;
    private javax.swing.JMenuItem clientes;
    private javax.swing.JComboBox con_fecha;
    private javax.swing.JComboBox con_matr;
    private javax.swing.JMenuItem concesionarios;
    private javax.swing.JPanel consultar;
    private javax.swing.JTextField ins_fecha;
    private javax.swing.JTextArea ins_log;
    private javax.swing.JComboBox ins_matr;
    private javax.swing.JComboBox ins_mecanico;
    private javax.swing.JTextField ins_n_horas;
    private javax.swing.JPanel insertar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_mecanico;
    private javax.swing.JLabel lbl_mecanico1;
    private javax.swing.JLabel lbl_mecanico2;
    private javax.swing.JLabel lbl_mecanico3;
    private javax.swing.JMenuItem mecanicos;
    private javax.swing.JMenu navegador;
    private javax.swing.JMenuItem reparaciones;
    private javax.swing.JTable tabla_consultas;
    // End of variables declaration//GEN-END:variables
}
