package modelo;
// Generated 01-feb-2015 15:32:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Automovil generated by hbm2java
 */
public class Automovil  implements java.io.Serializable {


     private String matricula;
     private Cliente cliente;
     private Concesionario concesionario;
     private String modelo;
     private String marca;
     private String color;
     private Set reparas = new HashSet(0);

    public Automovil() {
    }

	
    public Automovil(String matricula, Cliente cliente, Concesionario concesionario, String modelo, String marca, String color) {
        this.matricula = matricula;
        this.cliente = cliente;
        this.concesionario = concesionario;
        this.modelo = modelo;
        this.marca = marca;
        this.color = color;
    }
    public Automovil(String matricula, Cliente cliente, Concesionario concesionario, String modelo, String marca, String color, Set reparas) {
       this.matricula = matricula;
       this.cliente = cliente;
       this.concesionario = concesionario;
       this.modelo = modelo;
       this.marca = marca;
       this.color = color;
       this.reparas = reparas;
    }
   
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Concesionario getConcesionario() {
        return this.concesionario;
    }
    
    public void setConcesionario(Concesionario concesionario) {
        this.concesionario = concesionario;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public Set getReparas() {
        return this.reparas;
    }
    
    public void setReparas(Set reparas) {
        this.reparas = reparas;
    }




}


