package modelo;
// Generated 01-feb-2015 15:32:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private String dni;
     private String nombre;
     private String apellido1;
     private String apellido2;
     private String direccion;
     private int tlf;
     private Set automovils = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String dni, String nombre, String apellido1, String apellido2, String direccion, int tlf) {
        this.dni = dni;
        this.nombre = nombre;
        this.apellido1 = apellido1;
        this.apellido2 = apellido2;
        this.direccion = direccion;
        this.tlf = tlf;
    }
    public Cliente(String dni, String nombre, String apellido1, String apellido2, String direccion, int tlf, Set automovils) {
       this.dni = dni;
       this.nombre = nombre;
       this.apellido1 = apellido1;
       this.apellido2 = apellido2;
       this.direccion = direccion;
       this.tlf = tlf;
       this.automovils = automovils;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido1() {
        return this.apellido1;
    }
    
    public void setApellido1(String apellido1) {
        this.apellido1 = apellido1;
    }
    public String getApellido2() {
        return this.apellido2;
    }
    
    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public int getTlf() {
        return this.tlf;
    }
    
    public void setTlf(int tlf) {
        this.tlf = tlf;
    }
    public Set getAutomovils() {
        return this.automovils;
    }
    
    public void setAutomovils(Set automovils) {
        this.automovils = automovils;
    }




}


