package modelo;
// Generated 01-feb-2015 15:32:57 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ReparaId generated by hbm2java
 */
public class ReparaId  implements java.io.Serializable {


     private String dniMecanico;
     private String matricula;
     private int numHoras;
     private Date fecha;

    public ReparaId() {
    }

    public ReparaId(String dniMecanico, String matricula, int numHoras, Date fecha) {
       this.dniMecanico = dniMecanico;
       this.matricula = matricula;
       this.numHoras = numHoras;
       this.fecha = fecha;
    }
   
    public String getDniMecanico() {
        return this.dniMecanico;
    }
    
    public void setDniMecanico(String dniMecanico) {
        this.dniMecanico = dniMecanico;
    }
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    public int getNumHoras() {
        return this.numHoras;
    }
    
    public void setNumHoras(int numHoras) {
        this.numHoras = numHoras;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ReparaId) ) return false;
		 ReparaId castOther = ( ReparaId ) other; 
         
		 return ( (this.getDniMecanico()==castOther.getDniMecanico()) || ( this.getDniMecanico()!=null && castOther.getDniMecanico()!=null && this.getDniMecanico().equals(castOther.getDniMecanico()) ) )
 && ( (this.getMatricula()==castOther.getMatricula()) || ( this.getMatricula()!=null && castOther.getMatricula()!=null && this.getMatricula().equals(castOther.getMatricula()) ) )
 && (this.getNumHoras()==castOther.getNumHoras())
 && ( (this.getFecha()==castOther.getFecha()) || ( this.getFecha()!=null && castOther.getFecha()!=null && this.getFecha().equals(castOther.getFecha()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDniMecanico() == null ? 0 : this.getDniMecanico().hashCode() );
         result = 37 * result + ( getMatricula() == null ? 0 : this.getMatricula().hashCode() );
         result = 37 * result + this.getNumHoras();
         result = 37 * result + ( getFecha() == null ? 0 : this.getFecha().hashCode() );
         return result;
   }   


}


